### ISSUE TITLE
openai.error.InvalidRequestError: That model does not exist

### ISSUE THREAD

**Issue by xiuwei1026** [reidemeister94/confluence-gpt#1]
Did OpenAI shutdown or change something? Got below error when running the code.

2023-02-23 10:44:01,464 - openai - DEBUG - message='OpenAI API response' path=https://api.openai.com/v1/engines/text-chat-davinci-002-20230126/completions processing_ms=None request_id=f9f36e0cc30e11a8aa2b5ec82aa2ce1d response_code=404
2023-02-23 10:44:01,466 - openai - INFO - error_code=None error_message='That model does not exist' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
Traceback (most recent call last):
  File "create_page.py", line 103, in <module>
    main()
  File "create_page.py", line 83, in main
    chat_response = chatbot.ask(chat_message_content)["choices"][0]["text"]
  File "C:\Users\xwei\Anaconda3\lib\site-packages\revChatGPT\Official.py", line 107, in ask
    completion = self._get_completion(
  File "C:\Users\xwei\Anaconda3\lib\site-packages\revChatGPT\Official.py", line 47, in _get_completion
    return openai.Completion.create(
  File "C:\Users\xwei\Anaconda3\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\xwei\Anaconda3\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\xwei\Anaconda3\lib\site-packages\openai\api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\xwei\Anaconda3\lib\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\xwei\Anaconda3\lib\site-packages\openai\api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist

**Comment by reidemeister94** [comment]
Try now, everything should be fixed :)
